insert into skills (skillId, skill, skillLevel) values (1, 'NICET', '4');
insert into skills (skillId, skill, skillLevel) values (2, 'MRO Management', '5');
insert into skills (skillId, skill, skillLevel) values (3, 'Smart Metering', '3');
insert into skills (skillId, skill, skillLevel) values (4, 'NG-SDH', '3');
insert into skills (skillId, skill, skillLevel) values (5, 'VPython', '5');
insert into skills (skillId, skill, skillLevel) values (6, 'Radiology', '4');
insert into skills (skillId, skill, skillLevel) values (7, 'Jerseys', '1');
insert into skills (skillId, skill, skillLevel) values (8, 'Xbox 360', '5');
insert into skills (skillId, skill, skillLevel) values (9, 'Fashion Design', '5');
insert into skills (skillId, skill, skillLevel) values (10, 'Therapeutic Massage', '4');
insert into skills (skillId, skill, skillLevel) values (11, 'Luxury Travel', '4');
insert into skills (skillId, skill, skillLevel) values (12, 'CMTS', '4');
insert into skills (skillId, skill, skillLevel) values (13, 'EWS', '2');
insert into skills (skillId, skill, skillLevel) values (14, 'Clinical Nutrition', '5');
insert into skills (skillId, skill, skillLevel) values (15, 'Mergers &amp; Acquisitions', '5');
insert into skills (skillId, skill, skillLevel) values (16, 'Self-esteem', '4');
insert into skills (skillId, skill, skillLevel) values (17, 'CTM', '2');
insert into skills (skillId, skill, skillLevel) values (18, 'Critical Thinking', '5');
insert into skills (skillId, skill, skillLevel) values (19, 'OEM negotiations', '4');
insert into skills (skillId, skill, skillLevel) values (20, 'Xplan', '5');
insert into skills (skillId, skill, skillLevel) values (21, 'Fiction Writing', '5');
insert into skills (skillId, skill, skillLevel) values (22, 'PCR', '5');
insert into skills (skillId, skill, skillLevel) values (23, 'Fitness', '3');
insert into skills (skillId, skill, skillLevel) values (24, 'UAG', '3');
insert into skills (skillId, skill, skillLevel) values (25, 'CMake', '5');
insert into skills (skillId, skill, skillLevel) values (26, 'Obstetrics', '5');
insert into skills (skillId, skill, skillLevel) values (27, 'Mentoring', '5');
insert into skills (skillId, skill, skillLevel) values (28, 'AACR2', '5');
insert into skills (skillId, skill, skillLevel) values (29, 'Sales Effectiveness', '5');
insert into skills (skillId, skill, skillLevel) values (30, 'Rent to Own', '3');
insert into skills (skillId, skill, skillLevel) values (31, 'Rhino', '5');
insert into skills (skillId, skill, skillLevel) values (32, 'XPlanner', '5');
insert into skills (skillId, skill, skillLevel) values (33, 'Oil &amp; Gas Industry', '2');
insert into skills (skillId, skill, skillLevel) values (34, 'Junior Golf', '5');
insert into skills (skillId, skill, skillLevel) values (35, 'Xalan', '5');
insert into skills (skillId, skill, skillLevel) values (36, 'LSL', '5');
insert into skills (skillId, skill, skillLevel) values (37, '.htaccess', '2');
insert into skills (skillId, skill, skillLevel) values (38, 'Objective-C', '5');
insert into skills (skillId, skill, skillLevel) values (39, 'Microcontrollers', '5');
insert into skills (skillId, skill, skillLevel) values (40, 'Loan Origination', '5');
insert into skills (skillId, skill, skillLevel) values (41, 'NRSWA', '5');
insert into skills (skillId, skill, skillLevel) values (42, 'Sanction II', '5');
insert into skills (skillId, skill, skillLevel) values (43, 'Portuguese', '5');
insert into skills (skillId, skill, skillLevel) values (44, 'Working Capital Management', '5');
insert into skills (skillId, skill, skillLevel) values (45, 'Winning Others Over', '3');
insert into skills (skillId, skill, skillLevel) values (46, 'OOP', '4');
insert into skills (skillId, skill, skillLevel) values (47, 'Animal Work', '5');
insert into skills (skillId, skill, skillLevel) values (48, 'DBAccess', '5');
insert into skills (skillId, skill, skillLevel) values (49, 'Phase II', '4');
insert into skills (skillId, skill, skillLevel) values (50, 'Special Effects', '1');
insert into skills (skillId, skill, skillLevel) values (51, 'JDA', '4');
insert into skills (skillId, skill, skillLevel) values (52, 'At-risk', '3');
insert into skills (skillId, skill, skillLevel) values (53, 'JFreeChart', '5');
insert into skills (skillId, skill, skillLevel) values (54, 'Gym', '3');
insert into skills (skillId, skill, skillLevel) values (55, 'Athletic Training', '4');
insert into skills (skillId, skill, skillLevel) values (56, 'Ext JS', '5');
insert into skills (skillId, skill, skillLevel) values (57, 'Apartments', '5');
insert into skills (skillId, skill, skillLevel) values (58, 'Small Business Lending', '0');
insert into skills (skillId, skill, skillLevel) values (59, 'EHS', '1');
insert into skills (skillId, skill, skillLevel) values (60, 'Veterinary', '2');
insert into skills (skillId, skill, skillLevel) values (61, 'Research', '1');
insert into skills (skillId, skill, skillLevel) values (62, 'Kuka', '3');
insert into skills (skillId, skill, skillLevel) values (63, 'Product Marketing', '4');
insert into skills (skillId, skill, skillLevel) values (64, 'Key Opinion Leaders', '4');
insert into skills (skillId, skill, skillLevel) values (65, 'ICT Governance', '5');
insert into skills (skillId, skill, skillLevel) values (66, 'Irrigation', '5');
insert into skills (skillId, skill, skillLevel) values (67, 'Surgery', '3');
insert into skills (skillId, skill, skillLevel) values (68, 'Snoring', '3');
insert into skills (skillId, skill, skillLevel) values (69, 'Amazon EC2', '4');
insert into skills (skillId, skill, skillLevel) values (70, 'Lecturing', '5');
insert into skills (skillId, skill, skillLevel) values (71, 'Wedding Photography', '4');
insert into skills (skillId, skill, skillLevel) values (72, 'DDD', '5');
insert into skills (skillId, skill, skillLevel) values (73, 'Title Searches', '4');
insert into skills (skillId, skill, skillLevel) values (74, 'Software Project Management', '4');
insert into skills (skillId, skill, skillLevel) values (75, 'Omniture', '3');
insert into skills (skillId, skill, skillLevel) values (76, 'Participant Observation', '5');
insert into skills (skillId, skill, skillLevel) values (77, 'Golf', '5');
insert into skills (skillId, skill, skillLevel) values (78, 'Eye Tracking', '5');
insert into skills (skillId, skill, skillLevel) values (79, 'Regulatory Affairs', '5');
insert into skills (skillId, skill, skillLevel) values (80, 'Star-CCM+', '5');
insert into skills (skillId, skill, skillLevel) values (81, 'Jive', '5');
insert into skills (skillId, skill, skillLevel) values (82, 'Zoo', '4');
insert into skills (skillId, skill, skillLevel) values (83, 'FFE', '0');
insert into skills (skillId, skill, skillLevel) values (84, 'Urology', '1');
insert into skills (skillId, skill, skillLevel) values (85, 'EJB', '5');
insert into skills (skillId, skill, skillLevel) values (86, 'Vlookup', '4');
insert into skills (skillId, skill, skillLevel) values (87, 'MHE', '5');
insert into skills (skillId, skill, skillLevel) values (88, 'Guided Tours', '5');
insert into skills (skillId, skill, skillLevel) values (89, 'MCDBA', '0');
insert into skills (skillId, skill, skillLevel) values (90, 'WS-Federation', '5');
insert into skills (skillId, skill, skillLevel) values (91, 'JVC', '2');
insert into skills (skillId, skill, skillLevel) values (92, 'Digital TV', '5');
insert into skills (skillId, skill, skillLevel) values (93, 'Zsh', '4');
insert into skills (skillId, skill, skillLevel) values (94, 'Non-profit Administration', '5');
insert into skills (skillId, skill, skillLevel) values (95, 'Qt Creator', '2');
insert into skills (skillId, skill, skillLevel) values (96, 'International Business', '5');
insert into skills (skillId, skill, skillLevel) values (97, 'KVM Switches', '4');
insert into skills (skillId, skill, skillLevel) values (98, 'Android', '4');
insert into skills (skillId, skill, skillLevel) values (99, 'DFX', '5');
insert into skills (skillId, skill, skillLevel) values (100, 'PBIS', '5');
